import { readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../', import.meta.url);
const read = path => readFileSync(new URL(path, root), 'utf8');
const data = JSON.parse(read('data/venues.json'));
const logic = read('logic.js').replace(/^export /gm, '');
const app = read('app.js').replace(/^import .*?;\n/, '');
// A classic script with embedded data also works under file://, where browsers
// block ES module imports and fetch. Keep JSON and source modules authoritative.
const bundle = '// Generated by node scripts/build.mjs. Edit source files, not this bundle.\n' +
  '(() => {\n"use strict";\nconst embeddedVenues = ' + JSON.stringify(data) + ';\n' + logic + '\n' + app + '\n})();\n';
writeFileSync(new URL('tracker.js', root), bundle);
